// Builds src/data/arenaMetaTeams.json — the Arena Offense / Defense catalogue behind /arena.
//
// Regular arena has no public statistics source (swgt.io covers Siege/3MDC, swranking.com covers
// RTA only), so this is a curated list of established community compositions, NOT measured data:
// there are no win rates or clear times in it, and the UI says so. What this script guarantees is
// consistency with our own data: every monster name must exist in allMonsters.json, every leader
// text is taken from monsterSkillsData.json rather than typed by hand, and the light/dark flags are
// derived from the catalogue. It also writes src/data/arenaMonsterTraits.json (name → mechanics such as
// strip / revive / counter, read off the skill effects via src/utils/arenaTraits.js) for the counter search.
// Run: node scripts/build_arena_teams.mjs
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { monsterTraits, teamTraits } from '../src/utils/arenaTraits.js';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const monsters = JSON.parse(fs.readFileSync(path.join(root, 'src/data/allMonsters.json'), 'utf8'));
const skills = JSON.parse(fs.readFileSync(path.join(root, 'src/data/monsterSkillsData.json'), 'utf8'));
const byName = new Map(monsters.map((m) => [m.name.toLowerCase(), m]));
const skillByName = new Map(Object.values(skills).map((r) => [String(r.name || '').toLowerCase(), r]));
const traitsOf = (name) => monsterTraits(skillByName.get(String(name).toLowerCase()));

const AREA_TH = { Arena: 'อารีน่า', General: 'ทุกที่', Dungeon: 'ดันเจี้ยน', Guild: 'กิลด์', Element: 'ธาตุเดียวกัน' };
const ATTR_TH = { 'Attack Power': 'ATK', 'Attack Speed': 'SPD', HP: 'HP', Defense: 'DEF', 'Critical Rate': 'CRI Rate', Accuracy: 'ACC', Resistance: 'RES' };
const ELEMENT_TH = { water: 'น้ำ', fire: 'ไฟ', wind: 'ลม', light: 'แสง', dark: 'มืด' };
const elementTh = (name) => ELEMENT_TH[byName.get(name.toLowerCase())?.element] || '';

/** Leader text from the skill database, or a note that the lead does nothing in arena. */
function leaderOf(name) {
  const rec = skillByName.get(name.toLowerCase());
  const ls = rec?.ls;
  if (!ls || !ls.attribute) return { name, text: `${name} — ไม่มีลีดสกิล`, arena: false };
  const area = ls.area || 'General';
  const arenaUsable = area === 'Arena' || area === 'General' || area === 'Element';
  const scope = area === 'Element' ? `เฉพาะธาตุ${elementTh(name)}` : AREA_TH[area] || area;
  return { name, text: `${name} — ${ATTR_TH[ls.attribute] || ls.attribute} +${ls.amount}% (${scope})${arenaUsable ? '' : ' ⚠️ ไม่มีผลในอารีน่า'}`, arena: arenaUsable };
}

// ---------------------------------------------------------------------------------------------
// Curated compositions. slots[0] is the intended leader. tier = community-consensus strength
// (S/A/B), not a measured number. swaps = cheaper or alternative picks per slot.

const AO = [
  { id: 'ao-zaiross-tiana-galleon-kaki', tier: 'S', archetype: 'Fast Cleave', speed: 'คลีฟเทิร์นแรก',
    name: 'Zaiross Tiana Galleon Kaki', nameTh: 'ซาอิรอส เทียน่า กัลเลียน คาคิ (คลีฟมาตรฐาน)',
    slots: ['Zaiross', 'Tiana', 'Galleon', 'Kaki'],
    turnOrder: ['Tiana S3 ล้างบัฟทั้งทีม (ไม่สน RES) + เพิ่มเกจให้ทีมเรา', 'Galleon S3 เจาะเกราะ AoE + บัฟ ATK', 'Zaiross S3 กวาด AoE ดาเมจเต็ม', 'Kaki S2 เก็บงานตัวที่เหลือ'],
    runeGuidance: 'Tiana ต้องเร็วที่สุดในทีม (Swift/Will หรือ Shield/Will) → Galleon เร็วรองลงมา (Shield/Will) → Zaiross/Kaki Rage หรือ Fatal/Blade เน้น ATK% CD% ATK%',
    bestAgainst: 'ทีมรับที่ช้ากว่า Tiana, ทีมพึ่งบัฟ (Woosa/Chloe) เพราะ Tiana ล้างก่อน', avoidAgainst: 'ทีมรับลีด SPD 33% ที่มีตัวตัดเกจก่อน Tiana (Clara/Triton/Amduat) และทีมมี Will ครบพร้อม Nemesis',
    description: 'สูตรคลีฟที่ใช้กันมากที่สุด: ล้าง → เจาะเกราะ → ระเบิด แพ้เกือบทางเดียวคือถูกแซงเทิร์นแรก',
    swaps: { Kaki: ['Lushen', 'Julie'], Zaiross: ['Lushen', 'Kaki'], Galleon: ['Bastet', 'Sekhmet'] } },
  { id: 'ao-zaiross-tiana-galleon-lushen', tier: 'S', archetype: 'Fast Cleave', speed: 'คลีฟเทิร์นแรก',
    name: 'Zaiross Tiana Galleon Lushen', nameTh: 'ซาอิรอส เทียน่า กัลเลียน ลูเชน',
    slots: ['Zaiross', 'Tiana', 'Galleon', 'Lushen'],
    turnOrder: ['Tiana S3 ล้างบัฟ + เพิ่มเกจ', 'Galleon S3 เจาะเกราะ + บัฟ ATK', 'Lushen S3 Amputation Magic เจาะ DEF', 'Zaiross S3 ปิดเกม'],
    runeGuidance: 'เหมือนสูตร Kaki แต่ Lushen ต้องการ ATK% สูงกว่า (Rage/Blade หรือ Fatal/Blade) เพราะไม่มี Passive ช่วย',
    bestAgainst: 'ทีมรับที่พึ่ง DEF สูง (Skogul/Tractor) เพราะ Lushen เจาะเกราะ', avoidAgainst: 'ทีมรับที่เร็วกว่า Tiana หรือมี Will + ตัวตัดเทิร์น',
    description: 'สลับ Kaki เป็น Lushen เมื่อเจอกำแพง DEF สูง ดาเมจ Lushen ไม่แคร์เกราะ',
    swaps: { Lushen: ['Kaki'], Zaiross: ['Kaki', 'Julie'] } },
  { id: 'ao-oberon-tiana-galleon-lushen', tier: 'S', archetype: 'Fast Cleave', speed: 'คลีฟเทิร์นแรก', ldNote: 'ลีดแสง 44% ATK',
    name: 'Oberon Tiana Galleon Lushen', nameTh: 'โอเบอรอน เทียน่า กัลเลียน ลูเชน (ลีดแสง +44%)',
    slots: ['Oberon', 'Tiana', 'Galleon', 'Lushen'],
    turnOrder: ['Tiana S3 ล้างบัฟ + เพิ่มเกจ', 'Galleon S3 เจาะเกราะ + บัฟ ATK', 'Lushen S3 กวาด', 'Oberon S3 Light of Judgement เจาะ DEF เก็บตัวสุดท้าย + ตัวเองอมตะ'],
    runeGuidance: 'Oberon ลีด ATK +44% ในอารีน่า (สูงสุดในเกม) ใส่ Swift/Will ให้ทันตาม Galleon ก็พอ ดาเมจมาจาก Lushen/Galleon',
    bestAgainst: 'ทุกทีมที่ Tiana ทัน — ลีด 44% ทำให้ Lushen ตัวเดียวก็ฆ่าได้', avoidAgainst: 'ทีม SPD 33% ที่แซง Tiana',
    description: 'อัปเกรดจากสูตร Zaiross: Oberon ให้ลีดอารีน่า ATK 44% แทน 33% และมี S3 เจาะเกราะเก็บงาน',
    swaps: { Oberon: ['Zaiross', 'Amduat'], Lushen: ['Kaki', 'Zaiross'] } },
  { id: 'ao-vanessa-tiana-galleon-zaiross', tier: 'S', archetype: 'Speed-lead Cleave', speed: 'คลีฟเทิร์นแรก',
    name: 'Vanessa Tiana Galleon Zaiross', nameTh: 'วาเนสซ่า เทียน่า กัลเลียน ซาอิรอส (ลีด SPD 33%)',
    slots: ['Vanessa', 'Tiana', 'Galleon', 'Zaiross'],
    turnOrder: ['Tiana S3 ล้างบัฟ + เพิ่มเกจ', 'Galleon S3 เจาะเกราะ + บัฟ ATK', 'Zaiross S3 กวาด', 'Vanessa S2 ล้างบัฟ/เจาะเกราะเดี่ยวเก็บงาน (S3 ชุบทีมถ้าพลาด)'],
    runeGuidance: 'ใช้เมื่อฝ่ายรับมีลีด SPD 33%: ลีด Vanessa ทำให้ Tiana ยังแซงได้โดยไม่ต้องเพิ่มสปีดรูน Vanessa เอง Vio/Will พอ',
    bestAgainst: 'ทีมรับลีด SPD 33% (Psamathe/Oliver/Vanessa) ที่สูตร Zaiross ลีดแซงไม่ทัน', avoidAgainst: 'ทีมรับที่ Tiana แซงอยู่แล้ว — เสียลีด ATK ไปเปล่า ๆ',
    description: 'สลับลีด ATK เป็นลีด SPD 33% เมื่อสงครามสปีดสูสี ยอมเสียดาเมจเพื่อให้ได้เทิร์นแรกชัวร์',
    swaps: { Vanessa: ['Psamathe', 'Oliver'], Zaiross: ['Lushen', 'Kaki'] } },
  { id: 'ao-psamathe-tiana-galleon-lushen', tier: 'A', archetype: 'Speed-lead Cleave', speed: 'คลีฟเทิร์นแรก',
    name: 'Psamathe Tiana Galleon Lushen', nameTh: 'ซามาเธ่ เทียน่า กัลเลียน ลูเชน',
    slots: ['Psamathe', 'Tiana', 'Galleon', 'Lushen'],
    turnOrder: ['Tiana S3 ล้างบัฟ', 'Galleon S3 เจาะเกราะ', 'Lushen S3 กวาด', 'Psamathe S2 เพิ่มคูลดาวน์ + ลดสปีดตัวรอด (Passive ล้างบัฟ+ชุบถ้าพลาด)'],
    runeGuidance: 'Psamathe Vio/Will ใส่เพื่อลีดกับประกันพลาด ไม่ต้องดาเมจ',
    bestAgainst: 'ทีมรับ SPD 33% และทีมที่พึ่งคูลดาวน์สกิลตัวเดียว', avoidAgainst: 'ทีมกำแพงลากยาวที่คลีฟรอบเดียวไม่ตาย',
    description: 'ลีด SPD 33% แบบน้ำ พร้อมประกัน: ถ้าคลีฟไม่จบ Psamathe ยืดเกมด้วยคูลดาวน์',
    swaps: { Psamathe: ['Vanessa', 'Oliver'] } },
  { id: 'ao-oliver-tiana-galleon-kaki', tier: 'A', archetype: 'Speed-lead Cleave', speed: 'คลีฟเทิร์นแรก',
    name: 'Oliver Tiana Galleon Kaki', nameTh: 'โอลิเวอร์ เทียน่า กัลเลียน คาคิ',
    slots: ['Oliver', 'Tiana', 'Galleon', 'Kaki'],
    turnOrder: ['Tiana S3 ล้างบัฟ', 'Galleon S3 เจาะเกราะ', 'Kaki S2 กวาด', 'Oliver S3 ดันคูลดาวน์ + ดูดเกจตัวรอด'],
    runeGuidance: 'Oliver Swift/Will เร็วเป็นอันดับ 3 ของทีม ใช้ล็อกตัวรอดไม่ให้ได้เทิร์น',
    bestAgainst: 'ทีมรับ SPD 33% ที่มีตัวชุบ (Perna/Nana) — Oliver ดันคูลดาวน์ให้ชุบไม่ทัน', avoidAgainst: 'ทีมกำแพง HP หนามาก',
    description: 'ลีดสปีดสายลม + Oliver ทำหน้าที่ปิดประตูหลังคลีฟ',
    swaps: { Oliver: ['Psamathe', 'Vanessa'], Kaki: ['Lushen'] } },
  { id: 'ao-amduat-tiana-galleon-lushen', tier: 'A', archetype: 'Fast Cleave', speed: 'คลีฟเทิร์นแรก', ldNote: 'ลีดมืด 4★ ATK 33%',
    name: 'Amduat Tiana Galleon Lushen', nameTh: 'อัมดูอัต เทียน่า กัลเลียน ลูเชน (ลีดมืด 4★)',
    slots: ['Amduat', 'Tiana', 'Galleon', 'Lushen'],
    turnOrder: ['Tiana S3 ล้างบัฟ', 'Galleon S3 เจาะเกราะ', 'Lushen S3 กวาด', 'Amduat S2 ลดเกจ+ลดสปีด AoE ตัวรอด (Passive ได้เกจ+ล้างบัฟเมื่อโดนบัฟ)'],
    runeGuidance: 'Amduat Swift/Will หรือ Vio/Will เร็วพอตาม Galleon',
    bestAgainst: 'ทีมรับที่ชอบเปิดบัฟก่อน (Amduat ได้เกจ+ล้าง)', avoidAgainst: 'ทีมที่แซง Tiana',
    description: 'ทางเลือกลีด ATK 33% จากมอนแสง-มืด 4★ สำหรับคนไม่มี Zaiross/Oberon',
    swaps: { Amduat: ['Zaiross', 'Oberon'] } },
  { id: 'ao-bernard-galleon-lushen-lushen', tier: 'A', archetype: 'Budget Cleave', speed: 'คลีฟเทิร์นแรก',
    name: 'Bernard Galleon Lushen Lushen', nameTh: 'เบอร์นาร์ด กัลเลียน ลูเชน ×2 (คลีฟประหยัด)',
    slots: ['Bernard', 'Galleon', 'Lushen', 'Lushen'],
    turnOrder: ['Bernard S3 เพิ่มเกจ+สปีดทั้งทีม', 'Galleon S3 เจาะเกราะ + บัฟ ATK', 'Lushen S3', 'Lushen S3'],
    runeGuidance: 'Bernard Swift/Focus เร็วสุด, Galleon Swift/Will, Lushen ×2 Fatal/Blade หรือ Rage/Blade ATK% CD% ATK% เน้นดาเมจล้วน',
    bestAgainst: 'ทีมรับที่ไม่มีบัฟป้องกันเปิดก่อน ทีมกำแพง DEF (Lushen เจาะเกราะ)', avoidAgainst: 'ทีมที่มี Will/ภูมิคุ้มกันตั้งแต่เริ่ม (ไม่มีตัวล้างบัฟ) และทีมเร็วกว่า Bernard',
    description: 'สูตรคลาสสิกไม่ต้องมี nat5: Bernard ลีดธาตุลม +30% ATK ให้ Lushen ทั้งสอง ทำได้ตั้งแต่ระดับกลาง',
    swaps: { Bernard: ['Megan', 'Tiana'], Galleon: ['Bastet', 'Megan'] } },
  { id: 'ao-megan-galleon-lushen-kaki', tier: 'B', archetype: 'Budget Cleave', speed: 'คลีฟเทิร์นแรก',
    name: 'Megan Galleon Lushen Kaki', nameTh: 'เมแกน กัลเลียน ลูเชน คาคิ',
    slots: ['Megan', 'Galleon', 'Lushen', 'Kaki'],
    turnOrder: ['Megan S3 เพิ่มเกจ + บัฟ ATK/DEF ทั้งทีม', 'Galleon S3 เจาะเกราะ', 'Lushen S3', 'Kaki S2'],
    runeGuidance: 'Megan ลีดอารีน่า ATK 21% + บัฟ ATK ซ้อนกับ Galleon ใส่ Swift/Will เร็วสุด',
    bestAgainst: 'ทีมรับระดับกลางที่ไม่มีตัวล้างบัฟก่อน', avoidAgainst: 'ทีมรับที่เปิดภูมิคุ้มกัน/Will เพราะสูตรนี้ไม่มีตัวล้าง',
    description: 'สูตรประหยัดอีกแบบ ใช้ลีดอารีน่าของ Megan (3★) แทน Bernard',
    swaps: { Megan: ['Bernard'], Kaki: ['Lushen', 'Julie'] } },
  { id: 'ao-chloe-galleon-lushen-lushen', tier: 'A', archetype: 'Immunity Cleave', speed: 'คลีฟเทิร์นแรก',
    name: 'Chloe Galleon Lushen Lushen', nameTh: 'โคลอี้ กัลเลียน ลูเชน ×2 (คลีฟอมตะ)',
    slots: ['Chloe', 'Galleon', 'Lushen', 'Lushen'],
    turnOrder: ['Chloe S3 ภูมิคุ้มกัน + อมตะทั้งทีม', 'Galleon S3 เจาะเกราะ', 'Lushen S3', 'Lushen S3'],
    runeGuidance: 'Chloe ลีดอารีน่า SPD 20% ต้องเร็วที่สุด (Swift/Will) ที่เหลือเหมือนสูตร Bernard',
    bestAgainst: 'ทีมรับที่พึ่งตัวตัดเทิร์น/สตันเร็ว (Clara, Verad) — อมตะกันเทิร์นแรกไว้ก่อน', avoidAgainst: 'ทีมรับที่มีตัวล้างบัฟก่อนเทิร์นเรา (Tiana AD) หรือกำแพง Will+HP หนาที่คลีฟรอบเดียวไม่ตาย',
    description: 'แทนที่จะแข่งล้างบัฟ สูตรนี้ทำให้ทีมเราตายไม่ได้ 1 เทิร์นแล้วคลีฟ ใช้กับทีมรับสาย CC',
    swaps: { Chloe: ['Fran', 'Woosa'], Galleon: ['Bastet'] } },
  { id: 'ao-leo-galleon-lushen-lushen', tier: 'S', archetype: 'Anti-speed Cleave', speed: 'คลีฟเทิร์นแรก',
    name: 'Leo Galleon Lushen Lushen', nameTh: 'ลีโอ กัลเลียน ลูเชน ×2 (แก้ทีมสปีด)',
    slots: ['Leo', 'Galleon', 'Lushen', 'Lushen'],
    turnOrder: ['Leo Passive ลดเกจศัตรูที่เร็วกว่า Leo ทุกครั้งที่มันได้เทิร์น', 'Galleon S3 เจาะเกราะ', 'Lushen S3', 'Lushen S3 (Leo S2 เจาะ DEF เก็บงาน)'],
    runeGuidance: 'Leo ไม่ต้องเร็ว! ตั้งใจให้ช้ากว่าตัวรับเพื่อให้ Passive ทำงาน Vio/Will HP% แล้วให้ Galleon เร็วกว่าฝ่ายรับ ลีด DEF ธาตุลมของ Leo ไม่เกี่ยว',
    bestAgainst: 'ทีมรับลีด SPD 33% และทีมดักสปีดทุกชนิด (Psamathe/Clara/Savannah)', avoidAgainst: 'ทีมรับที่ช้าอยู่แล้ว (Passive ไม่ทำงาน) และทีมกำแพงลากยาว',
    description: 'คำตอบมาตรฐานของทีมรับสปีด: Leo ทำให้ความเร็วของฝ่ายรับกลายเป็นโทษ Galleon+Lushen ปิดตามปกติ',
    swaps: { Lushen: ['Kaki', 'Zaiross'], Galleon: ['Tiana', 'Bastet'] } },
  { id: 'ao-seara-tiana-liebli-bastet', tier: 'S', archetype: 'Bomb Cleave', speed: 'คลีฟ 1-2 รอบ', ldNote: 'Liebli มืด 4★',
    name: 'Seara Tiana Liebli Bastet', nameTh: 'เซอาร่า เทียน่า ลีบลี บาสเต็ต (บอมบ์คลีฟ)',
    slots: ['Seara', 'Tiana', 'Liebli', 'Bastet'],
    turnOrder: ['Tiana S3 ล้างบัฟ + เพิ่มเกจ', 'Bastet S3 โล่ + เพิ่มเกจ + บัฟ ATK (S2 เจาะเกราะถ้าจำเป็น)', 'Liebli S2 วางบอมบ์ AoE', 'Seara S3 จุดบอมบ์ทั้งหมด + ดูดเกจ (S2 วางบอมบ์+ได้เทิร์นเพิ่ม)'],
    runeGuidance: 'Tiana เร็วสุด → Bastet → Liebli → Seara (Seara ต้องได้ต่อจาก Liebli ทันที) บอมบ์ไม่สนเกราะ ใช้ HP%/ACC% ได้ ไม่ต้อง CD',
    bestAgainst: 'ทีมกำแพง DEF สูง, ทีมลากเกม (Camilla/Rina/Chasun), ทีมมี Will ที่คลีฟธรรมดาไม่ตาย', avoidAgainst: 'ทีมที่มีตัวล้างดีบัฟ/ภูมิคุ้มกันซ้ำ (Woosa/Velajuel) และทีมเร็วกว่า Tiana',
    description: 'ดาเมจบอมบ์ไม่แคร์ DEF/โล่ จึงเป็นคำตอบของทีมรับสายถึก Seara ระเบิดบอมบ์ทั้งกระดานในเทิร์นเดียว',
    swaps: { Liebli: ['Jojo', 'Malaka', 'Sian'], Bastet: ['Galleon', 'Megan'], Tiana: ['Triton'] } },
  { id: 'ao-seara-tiana-liebli-malaka', tier: 'A', archetype: 'Bomb Cleave', speed: 'คลีฟ 1-2 รอบ', ldNote: 'Liebli มืด 4★',
    name: 'Seara Tiana Liebli Malaka', nameTh: 'เซอาร่า เทียน่า ลีบลี มาลาก้า (บอมบ์คู่)',
    slots: ['Seara', 'Tiana', 'Liebli', 'Malaka'],
    turnOrder: ['Tiana S3 ล้างบัฟ', 'Malaka S2 บอมบ์ AoE + เพิ่มเกจทีม', 'Liebli S2 บอมบ์ AoE', 'Seara S3 จุดบอมบ์ 2 ชั้น'],
    runeGuidance: 'Malaka และ Liebli ต้องมี ACC พอติดบอมบ์ (Malaka ลีด ACC ธาตุน้ำไม่ช่วยลม/มืด ใช้รูน Focus)',
    bestAgainst: 'กำแพง HP หนามากที่บอมบ์ชุดเดียวไม่พอ', avoidAgainst: 'ทีมที่มีตัวล้างดีบัฟก่อน Seara ได้เทิร์น',
    description: 'บอมบ์สองชั้นสำหรับกำแพงที่หนาเป็นพิเศษ แลกกับไม่มีบัฟป้องกันจาก Bastet',
    swaps: { Malaka: ['Jojo', 'Bastet'], Liebli: ['Jojo'] } },
  { id: 'ao-seara-tiana-jojo-bastet', tier: 'A', archetype: 'Bomb Cleave', speed: 'คลีฟ 1-2 รอบ',
    name: 'Seara Tiana Jojo Bastet', nameTh: 'เซอาร่า เทียน่า โจโจ้ บาสเต็ต (บอมบ์ไม่ใช้ LD)',
    slots: ['Seara', 'Tiana', 'Jojo', 'Bastet'],
    turnOrder: ['Tiana S3 ล้างบัฟ', 'Bastet S3 โล่+เกจ+ATK', 'Jojo S2 บอมบ์ AoE (S3 ล้างบัฟ+เผาถ้าจำเป็น)', 'Seara S3 จุดบอมบ์'],
    runeGuidance: 'Jojo แทน Liebli ได้เกือบเท่ากัน (บอมบ์ AoE เหมือนกัน) แต่ไม่มี Passive สวนกลับ',
    bestAgainst: 'เหมือนสูตร Liebli', avoidAgainst: 'เหมือนสูตร Liebli',
    description: 'บอมบ์คลีฟฉบับไม่มีมอนมืด: Jojo (ไฟ 4★) วางบอมบ์ AoE ได้เหมือน Liebli',
    swaps: { Jojo: ['Liebli', 'Malaka'] } },
  { id: 'ao-seara-tiana-galleon-liebli', tier: 'A', archetype: 'Bomb Cleave', speed: 'คลีฟ 1-2 รอบ', ldNote: 'Liebli มืด 4★',
    name: 'Seara Tiana Galleon Liebli', nameTh: 'เซอาร่า เทียน่า กัลเลียน ลีบลี',
    slots: ['Seara', 'Tiana', 'Galleon', 'Liebli'],
    turnOrder: ['Tiana S3 ล้างบัฟ', 'Galleon S3 เจาะเกราะ + ATK', 'Liebli S2 บอมบ์', 'Seara S3 จุดบอมบ์ (ดาเมจ Seara เองแรงขึ้นจากเจาะเกราะ)'],
    runeGuidance: 'Seara ใส่ ATK% บ้างเพราะ S3 มีดาเมจตรงหลังจุดบอมบ์',
    bestAgainst: 'ทีมรับผสมถึก+ตัวตี ที่บอมบ์อย่างเดียวช้าไป', avoidAgainst: 'ทีมล้างดีบัฟ',
    description: 'ลูกผสมบอมบ์+เจาะเกราะ จบเร็วกว่าบอมบ์ล้วนเมื่อกำแพงไม่หนาเกิน',
    swaps: { Liebli: ['Jojo'], Galleon: ['Bastet'] } },
  { id: 'ao-giana-galleon-lushen-lushen', tier: 'S', archetype: 'LD Control Cleave', speed: 'คลีฟเทิร์นแรก', ldNote: 'Giana มืด 5★',
    name: 'Giana Galleon Lushen Lushen', nameTh: 'เกียน่า กัลเลียน ลูเชน ×2 (คลีฟสายมืด)',
    slots: ['Giana', 'Galleon', 'Lushen', 'Lushen'],
    turnOrder: ['Giana S3 Critical Error ล้างบัฟ + สตัน AoE', 'Galleon S3 เจาะเกราะ + ATK', 'Lushen S3', 'Lushen S3'],
    runeGuidance: 'Giana ลีด ATK 33% ทุกที่ ต้องเร็วสุดและ ACC พอให้สตันติด (Swift/Will หรือ Vio/Will ACC%)',
    bestAgainst: 'ทีมรับที่พึ่ง Will/ภูมิคุ้มกัน (Giana ล้างแล้วสตันในสกิลเดียว)', avoidAgainst: 'ทีมรับ RES สูง (Katarina ลีด RES 55%) ที่สตันไม่ติด',
    description: 'Giana ทำงานของ Tiana และตัวสตันพร้อมกัน แถมให้ลีด ATK 33% — คลีฟที่ปลอดภัยที่สุดถ้ามีตัวมืดนี้',
    swaps: { Giana: ['Tiana'], Lushen: ['Kaki', 'Zaiross'] } },
  { id: 'ao-poseidon-tiana-charlotte-zaiross', tier: 'A', archetype: 'ATB Lock Cleave', speed: 'คลีฟ 1-2 รอบ',
    name: 'Poseidon Tiana Charlotte Zaiross', nameTh: 'โพไซดอน เทียน่า ชาร์ล็อต ซาอิรอส (ล็อกเกจ)',
    slots: ['Poseidon', 'Tiana', 'Charlotte', 'Zaiross'],
    turnOrder: ['Tiana S3 ล้างบัฟ + เพิ่มเกจ', 'Poseidon S3 ลดเกจ + ลดสปีด AoE', 'Charlotte S3 ลดเกจ AoE + Glancing + เพิ่มเกจทีมเรา', 'Zaiross S3 กวาด แล้ววนลูปกดเกจต่อ'],
    runeGuidance: 'Poseidon ลีด ATK 33% ทุกที่ Poseidon/Charlotte Swift/Focus ACC% ให้ลดเกจติด',
    bestAgainst: 'ทีมรับรูน Nemesis/Revenge และทีมพึ่ง Perna/Nana ชุบ — ฝ่ายรับไม่ได้เทิร์นเลย', avoidAgainst: 'ทีมรับที่มี RES สูงหรือ Will พร้อม Immune ซ้ำ',
    description: 'แทนที่จะรีบฆ่า สูตรนี้ไม่ให้ฝ่ายรับได้เทิร์น เหมาะกับทีมรับที่ตอบโต้เมื่อโดนตี',
    swaps: { Charlotte: ['Verad', 'Ganymede'], Zaiross: ['Lushen'] } },
  { id: 'ao-ganymede-tiana-galleon-lushen', tier: 'A', archetype: 'ATB Lock Cleave', speed: 'คลีฟ 1-2 รอบ',
    name: 'Ganymede Tiana Galleon Lushen', nameTh: 'แกนีมีด เทียน่า กัลเลียน ลูเชน',
    slots: ['Ganymede', 'Tiana', 'Galleon', 'Lushen'],
    turnOrder: ['Tiana S3 ล้างบัฟ', 'Ganymede S3 ลดเกจ + เพิ่มคูลดาวน์ AoE (ไม่สน RES)', 'Galleon S3 เจาะเกราะ', 'Lushen S3'],
    runeGuidance: 'Ganymede ลีด ACC 55% อารีน่า (ช่วย Galleon/Tiana ติดแน่น) Swift/Will',
    bestAgainst: 'ทีมรับที่พึ่งสกิล 3 ตัวเดียว (Woosa S3, Perna) — คูลดาวน์โดนดันจนใช้ไม่ทัน', avoidAgainst: 'ทีมกำแพงที่ไม่พึ่งสกิลคูลดาวน์',
    description: 'ควบคุมสองชั้น: ล้างบัฟแล้วดันคูลดาวน์ ทำให้ทีมรับใช้สกิลสำคัญไม่ได้ก่อนตาย',
    swaps: { Ganymede: ['Poseidon'], Lushen: ['Kaki', 'Zaiross'] } },
  { id: 'ao-jeogun-galleon-lushen-zaiross', tier: 'A', archetype: 'Art Master Cleave', speed: 'คลีฟเทิร์นแรก',
    name: 'Jeogun Galleon Lushen Zaiross', nameTh: 'จอกึน กัลเลียน ลูเชน ซาอิรอส',
    slots: ['Jeogun', 'Galleon', 'Lushen', 'Zaiross'],
    turnOrder: ['Jeogun S3 ล้างบัฟ + บัฟ ATK + เพิ่มเกจทั้งทีม (งานของ Tiana+Galleon รวมกัน)', 'Galleon S3 เจาะเกราะ', 'Zaiross S3 กวาด (ได้ลีดไฟ +50% ATK)', 'Lushen S3'],
    runeGuidance: 'Jeogun ลีด ATK 50% เฉพาะธาตุไฟ → Zaiross ได้เต็ม Jeogun Swift/Will เร็วสุด ACC%',
    bestAgainst: 'ทีมรับที่ Tiana ทำงานได้ — สูตรนี้ได้ประโยชน์เดียวกันแต่มีดาเมจ 3 ตัว', avoidAgainst: 'ทีมรับที่เร็วกว่า Jeogun (S3 เป็นดีบัฟ ต้อง ACC)',
    description: 'ทางเลือกสำหรับคนมี Jeogun ไม่มี Tiana: สกิล 3 ทำครบทั้งล้าง บัฟ และเกจ',
    swaps: { Jeogun: ['Tiana'], Lushen: ['Kaki'] } },
  { id: 'ao-triton-galleon-lushen-lushen', tier: 'A', archetype: 'Fast Cleave', speed: 'คลีฟเทิร์นแรก',
    name: 'Triton Galleon Lushen Lushen', nameTh: 'ไทรทัน กัลเลียน ลูเชน ×2',
    slots: ['Triton', 'Galleon', 'Lushen', 'Lushen'],
    turnOrder: ['Triton S3 ล้างบัฟ + ลดเกจ AoE', 'Galleon S3 เจาะเกราะ', 'Lushen S3', 'Lushen S3'],
    runeGuidance: 'Triton ต้องมี ACC สูงกว่า Tiana เพราะสกิลไม่ทะลุ RES (Swift/Focus ACC%)',
    bestAgainst: 'ทีมรับที่ไม่ได้ลีด RES และไม่มี Will', avoidAgainst: 'ทีม RES สูง / Will ครบ',
    description: 'ตัวล้างบัฟแทน Tiana ที่แถมลดเกจ แต่ต้องพึ่ง ACC',
    swaps: { Triton: ['Tiana', 'Jeogun'], Lushen: ['Kaki', 'Zaiross'] } },
  { id: 'ao-verad-tiana-galleon-lushen', tier: 'B', archetype: 'Freeze Cleave', speed: 'คลีฟ 1-2 รอบ',
    name: 'Verad Tiana Galleon Lushen', nameTh: 'เวราด เทียน่า กัลเลียน ลูเชน',
    slots: ['Verad', 'Tiana', 'Galleon', 'Lushen'],
    turnOrder: ['Tiana S3 ล้างบัฟ', 'Verad S3 ลดเกจ + แช่แข็ง AoE', 'Galleon S3 เจาะเกราะ', 'Lushen S3'],
    runeGuidance: 'Verad ลีด HP 33% ทุกที่ ใส่ Despair/Will ACC% ให้แช่แข็งติด',
    bestAgainst: 'ทีมรับที่คลีฟรอบเดียวไม่ตายแต่ CC ติด', avoidAgainst: 'ทีม RES สูง',
    description: 'ประกันภัยแบบแช่แข็ง: ถ้าคลีฟไม่จบ ฝ่ายรับก็ยังไม่ได้เทิร์น',
    swaps: { Verad: ['Poseidon', 'Ganymede'] } },
  { id: 'ao-jeanne-rakan-theomars-camilla', tier: 'A', archetype: 'Provoke Bruiser', speed: 'ลากยาว', ldNote: 'Jeanne แสง 5★',
    name: 'Jeanne Rakan Theomars Camilla', nameTh: 'ฌานน์ ราคาน ธีโอมาร์ส คามิลล่า (ยั่วยุแล้วทุบ)',
    slots: ['Jeanne', 'Rakan', 'Theomars', 'Camilla'],
    turnOrder: ['Jeanne S3 ยั่วยุ AoE + ได้เทิร์นเพิ่ม → S2 อมตะ', 'Rakan S2 บัฟ ATK+ภูมิคุ้มกัน / S3 ยั่วยุ+สวนกลับ', 'Theomars S2 เจาะเกราะเก็บทีละตัว', 'Camilla S1 ตี+ลดคูลดาวน์ตัวเอง Passive ฟื้นทีม'],
    runeGuidance: 'Jeanne ลีด RES 41% ทุกที่ Vio/Will HP% RES%, Rakan Vio/Will HP%, Theomars Vio/Will CD%, Camilla Vio/Will',
    bestAgainst: 'ทีมรับลากเกม/ฮีล (Chasun, Rina, Praha) และทีมที่พึ่งตัวตีตัวเดียว', avoidAgainst: 'กำแพงชุบซ้ำ ๆ (Perna+Nana+Taranys) — ทุบทีละตัวไม่ทันชุบ',
    description: 'สำหรับทีมรับที่คลีฟฆ่าไม่ตาย: บังคับให้ตีแต่ Jeanne/Rakan แล้วค่อย ๆ เก็บทีละตัว',
    swaps: { Jeanne: ['Louise', 'Ritesh'], Camilla: ['Woosa', 'Feng Yan'] } },
  { id: 'ao-woosa-theomars-perna-tesarion', tier: 'A', archetype: 'Immunity Bruiser', speed: 'ลากยาว',
    name: 'Woosa Theomars Perna Tesarion', nameTh: 'วูซ่า ธีโอมาร์ส เพอร์น่า เทซาริออน',
    slots: ['Woosa', 'Theomars', 'Perna', 'Tesarion'],
    turnOrder: ['Woosa S3 ภูมิคุ้มกัน + โล่ทั้งทีม', 'Theomars S2 เจาะเกราะ', 'Tesarion S2 เจาะเกราะ (Passive Oblivion ปิด Passive ศัตรู)', 'Perna S2 ล้างบัฟตัวอันตราย, Passive ชุบทีม'],
    runeGuidance: 'Woosa ลีด ACC 41% ทุกที่ Vio/Will HP% SPD, Theomars/Tesarion Vio/Will CD%, Perna Vio/Will HP%',
    bestAgainst: 'ทีมรับสาย CC (Verad/Clara/Charlotte) และทีมพึ่ง Passive (Tesarion ปิด)', avoidAgainst: 'ทีมกำแพงลากยาวที่ฮีลไม่หยุด',
    description: 'บุกแบบไม่ต้องแข่งสปีด: กันตัวเองก่อนแล้วทุบด้วย Ifrit สองตัว มี Perna ประกันชีวิต',
    swaps: { Tesarion: ['Elsharion', 'Rakan'], Woosa: ['Chloe', 'Laima'] } },
  { id: 'ao-elsharion-woosa-perna-theomars', tier: 'A', archetype: 'LD Bruiser', speed: 'ลากยาว', ldNote: 'Elsharion แสง 5★',
    name: 'Elsharion Woosa Perna Theomars', nameTh: 'เอลชาริออน วูซ่า เพอร์น่า ธีโอมาร์ส',
    slots: ['Elsharion', 'Woosa', 'Perna', 'Theomars'],
    turnOrder: ['Woosa S3 ภูมิคุ้มกัน + โล่', 'Elsharion ตี → Passive ขโมยบัฟ + ดูดเกจ + เพิ่มสปีดตัวเอง', 'Theomars S2 เจาะเกราะ', 'Perna S2 ล้างบัฟ / ชุบ'],
    runeGuidance: 'Elsharion ลีด ATK 33% ทุกที่ Vio/Will ATK% CD% ATK% ตีบ่อยเพื่อขโมยบัฟ',
    bestAgainst: 'ทีมรับที่พึ่งบัฟ (โล่/ภูมิคุ้มกัน/ATK) — ขโมยมาเป็นของเรา', avoidAgainst: 'ทีมที่ไม่ใช้บัฟเลย (Passive ไม่ได้อะไร)',
    description: 'อิฟริตแสงเปลี่ยนบัฟของฝ่ายรับเป็นของเรา ยิ่งฝ่ายรับบัฟเยอะยิ่งแพ้เร็ว',
    swaps: { Elsharion: ['Tesarion'], Woosa: ['Chloe'] } },
];

const AD = [
  { id: 'ad-psamathe-clara-savannah-byungchul', tier: 'S', archetype: 'Speed Threat', style: 'ดักสปีด',
    counters: ['ao-leo-galleon-lushen-lushen', 'ao-vanessa-tiana-galleon-zaiross', 'ao-chloe-galleon-lushen-lushen'],
    name: 'Psamathe Clara Savannah Byungchul', nameTh: 'ซามาเธ่ คลาร่า ซาวันน่า บยองชอล (ดักสปีด 33%)',
    slots: ['Psamathe', 'Clara', 'Savannah', 'Byungchul'],
    winCondition: 'Clara ได้เทิร์นก่อนทีมบุก → S3 ล้างบัฟ + สตัน AoE → Savannah S3 เจาะเกราะ+ลดเกจ → Byungchul S2 ขโมยบัฟ+คริการันตี ทีมบุกที่ไม่มีลีด SPD 33% แซง Clara ยาก',
    runeBuilds: 'Clara Swift/Focus หรือ Swift/Will เร็วสุด ACC%, Savannah Vio/Will หรือ Swift SPD, Byungchul Vio/Nemesis HP% CD% HP% CR 70%+, Psamathe Despair/Will หรือ Vio/Will',
    counterTips: 'Leo Galleon Lushen ×2 (Leo ลงโทษความเร็ว), ทีมลีด SPD 33% ที่ Tiana ยังแซง Clara, หรือ Chloe อมตะเทิร์นแรก',
    description: 'ทีมรับดักสปีดที่พบบ่อยที่สุดในระดับสูง จุดอ่อนคือถ้าโดนแซง Clara ทีมไม่มีกำแพง',
    swaps: { Byungchul: ['Theomars', 'Dominic'], Savannah: ['Galleon', 'Ethna'], Psamathe: ['Oliver', 'Vanessa'] } },
  { id: 'ad-oliver-clara-galleon-theomars', tier: 'A', archetype: 'Speed Threat', style: 'ดักสปีด',
    counters: ['ao-leo-galleon-lushen-lushen', 'ao-vanessa-tiana-galleon-zaiross', 'ao-chloe-galleon-lushen-lushen'],
    name: 'Oliver Clara Galleon Theomars', nameTh: 'โอลิเวอร์ คลาร่า กัลเลียน ธีโอมาร์ส',
    slots: ['Oliver', 'Clara', 'Galleon', 'Theomars'],
    winCondition: 'Clara ล้างบัฟ+สตัน → Galleon เจาะเกราะ → Theomars/Oliver เก็บ Oliver S3 ดันคูลดาวน์ตัวรอดไม่ให้ตอบโต้',
    runeBuilds: 'Clara Swift/Focus, Galleon Swift/Will, Oliver Swift/Will, Theomars Vio/Will CD%',
    counterTips: 'Leo cleave หรือทีมบุกที่มี Will ครบ + ตัวล้างดีบัฟ (Clara สตันไม่ติด)',
    description: 'ดักสปีดสายบุกหนัก: ถ้า Clara ติด ทีมบุกตายในรอบเดียว',
    swaps: { Theomars: ['Byungchul', 'Lushen'], Oliver: ['Psamathe', 'Vanessa'] } },
  { id: 'ad-vanessa-clara-savannah-perna', tier: 'A', archetype: 'Speed Threat', style: 'ดักสปีด',
    counters: ['ao-leo-galleon-lushen-lushen', 'ao-seara-tiana-liebli-bastet', 'ao-oliver-tiana-galleon-kaki', 'ao-ganymede-tiana-galleon-lushen'],
    name: 'Vanessa Clara Savannah Perna', nameTh: 'วาเนสซ่า คลาร่า ซาวันน่า เพอร์น่า',
    slots: ['Vanessa', 'Clara', 'Savannah', 'Perna'],
    winCondition: 'เหมือนสูตร Psamathe แต่มี Perna ประกัน: ถ้าคลีฟไม่จบ Perna ชุบและ Vanessa S3 ชุบซ้ำได้',
    runeBuilds: 'Clara Swift/Focus, Savannah Vio/Will, Perna Vio/Will HP%, Vanessa Vio/Will',
    counterTips: 'บอมบ์คลีฟ (Seara) หรือ Oliver/Ganymede ดันคูลดาวน์ให้ชุบไม่ทัน',
    description: 'ดักสปีดที่ทนต่อการคลีฟไม่จบ เพราะมีชุบสองชั้น',
    swaps: { Perna: ['Nana', 'Taranys'], Vanessa: ['Psamathe'] } },
  { id: 'ad-psamathe-giana-woosa-perna', tier: 'S', archetype: 'LD Speed Threat', style: 'ดักสปีด', ldNote: 'Giana มืด 5★',
    counters: ['ao-leo-galleon-lushen-lushen', 'ao-vanessa-tiana-galleon-zaiross', 'ao-oliver-tiana-galleon-kaki', 'ao-ganymede-tiana-galleon-lushen'],
    name: 'Psamathe Giana Woosa Perna', nameTh: 'ซามาเธ่ เกียน่า วูซ่า เพอร์น่า (ดักสปีดสายมืด)',
    slots: ['Psamathe', 'Giana', 'Woosa', 'Perna'],
    winCondition: 'Giana S3 ล้างบัฟ+สตัน AoE ก่อนทีมบุกได้เทิร์น → Woosa ภูมิคุ้มกัน+โล่ → Perna ชุบ ทีมบุกที่ถูกสตันไม่มีทางกลับ',
    runeBuilds: 'Giana Swift/Will หรือ Vio/Will ACC%, Woosa Vio/Will HP%, Perna Vio/Will, Psamathe Vio/Will',
    counterTips: 'Katarina ลีด RES / Will ครบ + Chloe อมตะ, หรือ Leo cleave',
    description: 'Giana ทำงานของ Clara แต่ทนกว่าและมีดาเมจ ทีมนี้ทั้งดักสปีดและกำแพงในเวลาเดียวกัน',
    swaps: { Giana: ['Clara', 'Tiana'], Woosa: ['Chloe'] } },
  { id: 'ad-psamathe-tiana-skogul-perna', tier: 'A', archetype: 'Speed Strip', style: 'ดักสปีด',
    counters: ['ao-leo-galleon-lushen-lushen', 'ao-bernard-galleon-lushen-lushen', 'ao-seara-tiana-liebli-bastet'],
    name: 'Psamathe Tiana Skogul Perna', nameTh: 'ซามาเธ่ เทียน่า สโกกุล เพอร์น่า',
    slots: ['Psamathe', 'Tiana', 'Skogul', 'Perna'],
    winCondition: 'Tiana ล้างบัฟทีมบุก (Will/ภูมิคุ้มกันหาย) ก่อนมันได้เทิร์น → Skogul ยืนรับ → Perna ชุบ',
    runeBuilds: 'Tiana Swift/Will เร็วสุด, Skogul Vio/Will HP% DEF%, Perna Vio/Will, Psamathe Vio/Will',
    counterTips: 'Leo cleave, หรือทีมบุกที่ไม่พึ่งบัฟตอนเริ่ม (Bernard Lushen บัฟทีหลัง)',
    description: 'ใช้ Tiana ในฝั่งรับ: ทีมบุกที่พึ่งโล่/ภูมิคุ้มกันจะเปลือยทันที',
    swaps: { Skogul: ['Tractor', 'Khmun'], Tiana: ['Triton'] } },
  { id: 'ad-layla-skogul-woosa-perna', tier: 'A', archetype: 'Bruiser Wall', style: 'กำแพง',
    counters: ['ao-seara-tiana-liebli-bastet', 'ao-seara-tiana-jojo-bastet', 'ao-woosa-theomars-perna-tesarion', 'ao-zaiross-tiana-galleon-lushen'],
    name: 'Layla Skogul Woosa Perna', nameTh: 'เลย์ล่า สโกกุล วูซ่า เพอร์น่า (ลีด DEF 44%)',
    slots: ['Layla', 'Skogul', 'Woosa', 'Perna'],
    winCondition: 'ลีด DEF 44% ทำให้คลีฟฆ่าไม่ตาย → Layla Passive ใบ้ผู้โจมตี + ล้างบัฟ AoE → Woosa/Perna ลากเกมจนทีมบุกหมดแรง',
    runeBuilds: 'Layla Vio/Will HP% RES%, Skogul Vio/Will DEF% HP%, Woosa Vio/Will HP%, Perna Vio/Will HP%',
    counterTips: 'บอมบ์คลีฟ (ไม่สน DEF) หรือ Tesarion Oblivion ปิด Passive Layla',
    description: 'กำแพงที่ลงโทษการตี: ยิ่งตี Layla ยิ่งโดนใบ้',
    swaps: { Layla: ['Miles', 'Craka'], Skogul: ['Tractor'] } },
  { id: 'ad-miles-skogul-woosa-taranys', tier: 'A', archetype: 'Bruiser Wall', style: 'กำแพง',
    counters: ['ao-seara-tiana-liebli-bastet', 'ao-oliver-tiana-galleon-kaki', 'ao-ganymede-tiana-galleon-lushen'],
    name: 'Miles Skogul Woosa Taranys', nameTh: 'ไมล์ส สโกกุล วูซ่า ทารานีส',
    slots: ['Miles', 'Skogul', 'Woosa', 'Taranys'],
    winCondition: 'ลีด DEF 44% + Taranys ชุบซ้ำ (S3 ชุบทีม + Passive ชุบตัวเอง) Miles S2 ล้างบัฟ+สตันตัวอันตราย Passive เจาะเกราะ',
    runeBuilds: 'Miles Vio/Will SPD HP% HP%, Skogul Vio/Will, Woosa Vio/Will, Taranys Vio/Will HP%',
    counterTips: 'บอมบ์คลีฟ หรือ Oliver/Ganymede ดันคูลดาวน์ Taranys',
    description: 'กำแพงชุบไม่รู้จบ ทีมบุกต้องฆ่า Taranys ก่อนถึงจะเริ่มเกมได้',
    swaps: { Taranys: ['Perna', 'Nana'], Miles: ['Layla'] } },
  { id: 'ad-craka-skogul-rakan-woosa', tier: 'A', archetype: 'LD Wall', style: 'กำแพง', ldNote: 'Craka มืด 5★',
    counters: ['ao-seara-tiana-liebli-bastet', 'ao-elsharion-woosa-perna-theomars', 'ao-woosa-theomars-perna-tesarion'],
    name: 'Craka Skogul Rakan Woosa', nameTh: 'คราก้า สโกกุล ราคาน วูซ่า (กำแพงสายมืด)',
    slots: ['Craka', 'Skogul', 'Rakan', 'Woosa'],
    winCondition: 'ลีด DEF 44% + Craka S3 ชุบทั้งทีม/อมตะ + S2 เจาะเกราะขโมยบัฟ Rakan ยั่วยุสวนกลับ Woosa ภูมิคุ้มกัน',
    runeBuilds: 'Craka Vio/Will HP% DEF%, Rakan Vio/Will HP%, Skogul Vio/Will, Woosa Vio/Will',
    counterTips: 'บอมบ์คลีฟ หรือ Elsharion ขโมยบัฟ + Tesarion Oblivion',
    description: 'กำแพงมืดที่ชุบได้ทั้งทีมในสกิลเดียว บุกแบบคลีฟรอบเดียวไม่มีทางจบ',
    swaps: { Craka: ['Layla', 'Miles'], Rakan: ['Feng Yan'] } },
  { id: 'ad-tiana-skogul-woosa-perna', tier: 'A', archetype: 'Strip Wall', style: 'กำแพง',
    counters: ['ao-seara-tiana-liebli-bastet', 'ao-leo-galleon-lushen-lushen', 'ao-oberon-tiana-galleon-lushen'],
    name: 'Tiana Skogul Woosa Perna', nameTh: 'เทียน่า สโกกุล วูซ่า เพอร์น่า (ลีด DEF 44%)',
    slots: ['Tiana', 'Skogul', 'Woosa', 'Perna'],
    winCondition: 'ลีด DEF 44% ของ Tiana + S3 ล้างบัฟทีมบุก ทีมบุกที่พึ่งบัฟ (Bernard/Megan/Chloe) ทำอะไรไม่ได้',
    runeBuilds: 'Tiana Vio/Will เร็วปานกลาง HP%, Skogul Vio/Will, Woosa Vio/Will, Perna Vio/Will',
    counterTips: 'บอมบ์คลีฟ, Leo cleave, หรือทีมที่ Tiana ฝั่งบุกแซง Tiana ฝั่งรับ',
    description: 'ใช้ Tiana เป็นลีดกำแพง 44% DEF ไม่ใช่ตัวเร็ว จุดเด่นคือล้างบัฟทีมบุกซ้ำ ๆ',
    swaps: { Skogul: ['Tractor', 'Khmun'], Perna: ['Nana', 'Taranys'] } },
  { id: 'ad-brandia-skogul-woosa-perna', tier: 'B', archetype: 'HP Wall', style: 'กำแพง',
    counters: ['ao-seara-tiana-liebli-bastet', 'ao-seara-tiana-jojo-bastet', 'ao-seara-tiana-liebli-malaka'],
    name: 'Brandia Skogul Woosa Perna', nameTh: 'บรานเดีย สโกกุล วูซ่า เพอร์น่า (ลีด HP 44%)',
    slots: ['Brandia', 'Skogul', 'Woosa', 'Perna'],
    winCondition: 'ลีด HP 44% อารีน่า + Brandia S2 AoE Glancing/ลด ATK + เพิ่มเกจทีม ทีมบุกดาเมจตกจนฆ่าไม่ตาย',
    runeBuilds: 'Brandia Vio/Will HP% SPD, ที่เหลือ Vio/Will HP%',
    counterTips: 'บอมบ์คลีฟ (Glancing/ATK down ไม่มีผลกับบอมบ์)',
    description: 'กำแพงสาย HP ที่กดดาเมจฝ่ายบุกด้วย Glancing',
    swaps: { Brandia: ['Rigel', 'Xiao Lin'] } },
  { id: 'ad-katarina-woosa-skogul-theomars', tier: 'A', archetype: 'Anti-CC Wall', style: 'กำแพง',
    counters: ['ao-zaiross-tiana-galleon-kaki', 'ao-oberon-tiana-galleon-lushen', 'ao-seara-tiana-liebli-bastet'],
    name: 'Katarina Woosa Skogul Theomars', nameTh: 'คาทาริน่า วูซ่า สโกกุล ธีโอมาร์ส (ลีด RES 55%)',
    slots: ['Katarina', 'Woosa', 'Skogul', 'Theomars'],
    winCondition: 'ลีด RES 55% อารีน่า ทำให้สตัน/แช่แข็ง/ลดเกจของทีมบุกไม่ติด → Woosa ภูมิคุ้มกัน → Katarina S3 เจาะ DEF + S2 อมตะ, Theomars เก็บ',
    runeBuilds: 'Katarina Vio/Will ATK% CD% ATK% RES%, Woosa Vio/Will HP% RES%, Skogul Vio/Will, Theomars Vio/Will',
    counterTips: 'Tiana (ล้างบัฟไม่สน RES) + คลีฟดาเมจล้วน หรือบอมบ์ที่มี ACC สูงมาก',
    description: 'คำตอบของทีมบุกสาย CC/ล็อกเกจ: ดีบัฟติดยากมาก',
    swaps: { Theomars: ['Byungchul', 'Dominic'] } },
  { id: 'ad-jeanne-rakan-skogul-woosa', tier: 'S', archetype: 'Provoke Wall', style: 'กำแพง', ldNote: 'Jeanne แสง 5★',
    counters: ['ao-seara-tiana-liebli-bastet', 'ao-woosa-theomars-perna-tesarion', 'ao-oberon-tiana-galleon-lushen'],
    name: 'Jeanne Rakan Skogul Woosa', nameTh: 'ฌานน์ ราคาน สโกกุล วูซ่า (ยั่วยุกำแพง)',
    slots: ['Jeanne', 'Rakan', 'Skogul', 'Woosa'],
    winCondition: 'ลีด RES 41% + Jeanne S3 ยั่วยุ AoE บังคับทีมบุกตี Jeanne ที่อมตะ (S2) → Rakan S3 ยั่วยุ+สวนกลับ → Woosa ภูมิคุ้มกัน ทีมบุกเสียเทิร์นทั้งหมด',
    runeBuilds: 'Jeanne Vio/Will HP% DEF% HP% SPD, Rakan Vio/Will HP% CD% HP%, Skogul Vio/Will, Woosa Vio/Will',
    counterTips: 'Katarina/Will ครบ + Tiana ล้างอมตะ, Tesarion Oblivion ปิด Passive Rakan, หรือบอมบ์ที่ไม่สนยั่วยุ',
    description: 'กำแพงยั่วยุที่แข็งที่สุดถ้ามี Jeanne: ทีมบุกถูกบังคับให้ทำสิ่งที่ไม่อยากทำ',
    swaps: { Jeanne: ['Louise', 'Josephine'], Rakan: ['Feng Yan', 'Zeratu'] } },
  { id: 'ad-josephine-zeratu-laika-jager', tier: 'A', archetype: 'LD Counter Wall', style: 'กำแพง', ldNote: 'Josephine/Zeratu/Jager แสง-มืด',
    counters: ['ao-seara-tiana-liebli-bastet', 'ao-seara-tiana-jojo-bastet', 'ao-poseidon-tiana-charlotte-zaiross'],
    name: 'Josephine Zeratu Laika Jager', nameTh: 'โจเซฟีน เซราตู ไลก้า เยเกอร์ (กำแพงสวนกลับ)',
    slots: ['Josephine', 'Zeratu', 'Laika', 'Jager'],
    winCondition: 'ทุกตัวสวนกลับ: Josephine Passive โล่+สวนกลับ+เทิร์นเพิ่ม, Laika Passive สวนกลับ, Jager Passive สวนกลับ+สะสม ATK, Zeratu Passive ล้างบัฟ+ตีซ้ำ ทีมบุกที่ตีเยอะตายเอง',
    runeBuilds: 'Josephine Vio/Will HP% ACC%, Zeratu Vio/Will HP% CD%, Laika Vio/Will HP%, Jager Vio/Will DEF%',
    counterTips: 'บอมบ์คลีฟ (บอมบ์ไม่นับเป็นการโจมตี ไม่โดนสวน) หรือ ATB lock ไม่ให้ได้เทิร์นเลย',
    description: 'กำแพงแสง-มืดสายสวนกลับ ทีมบุกดาเมจตรงจะโดนสวนจนตายก่อน',
    swaps: { Zeratu: ['Rakan', 'Feng Yan'], Jager: ['Chow', 'Leo'] } },
  { id: 'ad-woosa-chasun-rina-camilla', tier: 'A', archetype: 'Stall', style: 'ลากเกม',
    counters: ['ao-seara-tiana-liebli-bastet', 'ao-jeanne-rakan-theomars-camilla', 'ao-seara-tiana-liebli-malaka'],
    name: 'Woosa Chasun Rina Camilla', nameTh: 'วูซ่า ชาซุน รีน่า คามิลล่า (ลากเกม)',
    slots: ['Woosa', 'Chasun', 'Rina', 'Camilla'],
    winCondition: 'ไม่มีใครตาย: Woosa ภูมิคุ้มกัน+โล่, Chasun ฮีล+ATK+ภูมิคุ้มกัน, Rina โล่ Passive, Camilla ฟื้นตัวเอง+ทีม ทีมบุกหมดเวลา/หมดแรงแล้วแพ้ทางเทคนิค',
    runeBuilds: 'ทุกตัว Vio/Will HP% (Camilla ใส่ Vio/Nemesis), Rina Vio/Will HP% RES%',
    counterTips: 'บอมบ์คลีฟ (Seara Tiana) หรือ Provoke bruiser (Jeanne Rakan Theomars) ทุบทีละตัว',
    description: 'ทีมรับที่ไม่ได้หวังชนะแต่หวังไม่แพ้ ทีมบุกคลีฟธรรมดาจะติดอยู่ที่นี่',
    swaps: { Rina: ['Fran', 'Mihael'], Chasun: ['Praha', 'Harmonia'] } },
  { id: 'ad-praha-chasun-rina-jeanne', tier: 'B', archetype: 'Stall', style: 'ลากเกม', ldNote: 'Jeanne แสง 5★',
    counters: ['ao-seara-tiana-liebli-bastet', 'ao-woosa-theomars-perna-tesarion'],
    name: 'Praha Chasun Rina Jeanne', nameTh: 'พราฮา ชาซุน รีน่า ฌานน์',
    slots: ['Praha', 'Chasun', 'Rina', 'Jeanne'],
    winCondition: 'Praha S2 ล้างบัฟ AoE + S3 ฮีล/หลับ, Jeanne ยั่วยุ+อมตะ, Chasun/Rina ฮีล ทีมบุกไม่มีจังหวะได้ดาเมจ',
    runeBuilds: 'Praha Vio/Will HP% ACC%, Jeanne Vio/Will, Chasun Vio/Will, Rina Vio/Will',
    counterTips: 'บอมบ์คลีฟ หรือ Woosa Theomars Perna Tesarion (ภูมิคุ้มกันกันหลับ + Oblivion)',
    description: 'ลากเกมแบบมี CC: Praha ทำให้ทีมบุกหลับและเสียบัฟ',
    swaps: { Jeanne: ['Woosa', 'Louise'] } },
  { id: 'ad-chloe-theomars-perna-camilla', tier: 'A', archetype: 'Immunity Wall', style: 'กำแพง',
    counters: ['ao-zaiross-tiana-galleon-kaki', 'ao-oberon-tiana-galleon-lushen', 'ao-giana-galleon-lushen-lushen'],
    name: 'Chloe Theomars Perna Camilla', nameTh: 'โคลอี้ ธีโอมาร์ส เพอร์น่า คามิลล่า',
    slots: ['Chloe', 'Theomars', 'Perna', 'Camilla'],
    winCondition: 'Chloe S3 อมตะ+ภูมิคุ้มกันก่อนทีมบุกได้เทิร์น (ลีด SPD 20%) → คลีฟรอบแรกสูญเปล่า → Theomars/Camilla ตอบโต้ Perna ชุบ',
    runeBuilds: 'Chloe Swift/Will เร็วสุด, Theomars Vio/Will, Perna Vio/Will, Camilla Vio/Nemesis',
    counterTips: 'Tiana (ล้างอมตะไม่สน RES) แล้วคลีฟ หรือทีมบุกที่เร็วกว่า Chloe',
    description: 'ทีมรับที่ทำให้คลีฟเทิร์นแรกเป็นศูนย์ ถ้าทีมบุกไม่มี Tiana',
    swaps: { Chloe: ['Fran', 'Woosa'], Camilla: ['Rakan'] } },
  { id: 'ad-skogul-nana-perna-taranys', tier: 'A', archetype: 'Revive Wall', style: 'กำแพง',
    counters: ['ao-oliver-tiana-galleon-kaki', 'ao-ganymede-tiana-galleon-lushen', 'ao-poseidon-tiana-charlotte-zaiross', 'ao-seara-tiana-liebli-bastet'],
    name: 'Skogul Nana Perna Taranys', nameTh: 'สโกกุล นาน่า เพอร์น่า ทารานีส (ชุบสามชั้น)',
    slots: ['Skogul', 'Nana', 'Perna', 'Taranys'],
    winCondition: 'ตายแล้วเกิดใหม่: Nana Passive ชุบทีม, Perna Passive ชุบตัวเอง, Taranys S3 ชุบทีม+Passive ชุบตัวเอง ทีมบุกฆ่าไม่หมดใน 1 รอบ = แพ้',
    runeBuilds: 'Skogul ลีด (DEF 22% ทุกที่ — ลีดของ Nana/Perna ใช้ไม่ได้ในอารีน่า) Vio/Will DEF%, Nana Vio/Will HP%, Perna Vio/Will HP%, Taranys Vio/Will HP%',
    counterTips: 'Oliver/Ganymede ดันคูลดาวน์ + ATB lock, หรือบอมบ์คลีฟที่ฆ่าครบพร้อมกัน',
    description: 'กำแพงชุบ 3 ชั้นสำหรับกันคลีฟ: ต้องฆ่าให้ครบ 4 ตัวในรอบเดียวเท่านั้น',
    swaps: { Skogul: ['Woosa', 'Rakan'] } },
  { id: 'ad-woosa-feng-yan-rakan-camilla', tier: 'A', archetype: 'Bruiser Wall', style: 'กำแพง',
    counters: ['ao-seara-tiana-liebli-bastet', 'ao-woosa-theomars-perna-tesarion', 'ao-seara-tiana-jojo-bastet'],
    name: 'Woosa Feng Yan Rakan Camilla', nameTh: 'วูซ่า เฟิงเยี่ยน ราคาน คามิลล่า',
    slots: ['Woosa', 'Feng Yan', 'Rakan', 'Camilla'],
    winCondition: 'Woosa ภูมิคุ้มกัน → Feng Yan Passive ลดดาเมจ+เกจ, S2 ล้างดีบัฟ+สวนกลับ → Rakan ยั่วยุ+สวนกลับ → Camilla ฟื้น ทีมบุกโดนสวนจนหมดแรง',
    runeBuilds: 'Feng Yan Vio/Will HP% DEF% HP%, Rakan Vio/Will HP% CD% HP%, Woosa Vio/Will, Camilla Vio/Nemesis',
    counterTips: 'บอมบ์คลีฟ หรือ Tesarion Oblivion ปิด Passive ทั้ง Feng Yan/Rakan',
    description: 'กำแพงบรุยเซอร์ไม่ใช้แสง-มืด: ทีมบุกสายตีตรงจะโดนสวนกลับตลอด',
    swaps: { 'Feng Yan': ['Zeratu', 'Mo Long'], Camilla: ['Perna'] } },
  { id: 'ad-leo-skogul-woosa-perna', tier: 'A', archetype: 'Anti-speed Wall', style: 'กำแพง',
    counters: ['ao-jeanne-rakan-theomars-camilla', 'ao-woosa-theomars-perna-tesarion', 'ao-seara-tiana-liebli-bastet'],
    name: 'Leo Skogul Woosa Perna', nameTh: 'ลีโอ สโกกุล วูซ่า เพอร์น่า (ลงโทษทีมเร็ว)',
    slots: ['Leo', 'Skogul', 'Woosa', 'Perna'],
    winCondition: 'Leo Passive ลดเกจทีมบุกที่เร็วกว่า Leo ทุกเทิร์น + ลีด DEF 50% ให้ Skogul (ลม) ทีมคลีฟสปีดเสียจังหวะ → Woosa/Perna ลากจนชนะ',
    runeBuilds: 'Leo Vio/Will HP% DEF% ช้าตั้งใจ, Skogul Vio/Will, Woosa Vio/Will, Perna Vio/Will',
    counterTips: 'ทีมบุกช้า (Bruiser) ที่ Passive ไม่ทำงาน หรือบอมบ์คลีฟ',
    description: 'ทีมรับที่กลับด้านสงครามสปีด: ทีมบุกยิ่งเร็วยิ่งเสียเปรียบ',
    swaps: { Leo: ['Chow'], Perna: ['Taranys'] } },
  { id: 'ad-xiao-lin-skogul-woosa-perna', tier: 'B', archetype: 'Budget Wall', style: 'กำแพง',
    counters: ['ao-oberon-tiana-galleon-lushen', 'ao-seara-tiana-liebli-bastet'],
    name: 'Xiao Lin Skogul Woosa Perna', nameTh: 'เสี่ยวหลิน สโกกุล วูซ่า เพอร์น่า (ลีด DEF 33% แบบ 4★)',
    slots: ['Xiao Lin', 'Skogul', 'Woosa', 'Perna'],
    winCondition: 'ลีด DEF 33% อารีน่าจากมอน 4★ + Xiao Lin S3 สวนกลับ/เจาะเกราะ Skogul ยืน Woosa/Perna ลาก',
    runeBuilds: 'Xiao Lin Vio/Will HP% DEF%, ที่เหลือ Vio/Will HP%',
    counterTips: 'คลีฟลีด ATK 44% (Oberon) หรือบอมบ์',
    description: 'กำแพงประหยัดสำหรับคนยังไม่มี Layla/Miles/Craka',
    swaps: { 'Xiao Lin': ['Rigel', 'Brandia'], Skogul: ['Tractor'] } },
  { id: 'ad-rigel-skogul-woosa-taranys', tier: 'B', archetype: 'Budget Wall', style: 'กำแพง',
    counters: ['ao-seara-tiana-liebli-bastet', 'ao-ganymede-tiana-galleon-lushen'],
    name: 'Rigel Skogul Woosa Taranys', nameTh: 'ริเกล สโกกุล วูซ่า ทารานีส (ลีด HP 33% แบบ 4★)',
    slots: ['Rigel', 'Skogul', 'Woosa', 'Taranys'],
    winCondition: 'ลีด HP 33% อารีน่า + Rigel Passive ต้านสตัน/แช่แข็ง + เพิ่มเกจเมื่อโดนตี → Taranys ชุบ',
    runeBuilds: 'Rigel Vio/Will HP% DEF%, Taranys Vio/Will HP%, ที่เหลือ Vio/Will',
    counterTips: 'บอมบ์คลีฟ หรือ Ganymede ดันคูลดาวน์ Taranys',
    description: 'กำแพงประหยัดอีกแบบ Rigel (4★) ให้ลีด HP อารีน่า',
    swaps: { Rigel: ['Xiao Lin', 'Brandia'] } },
  { id: 'ad-irene-skogul-woosa-perna', tier: 'A', archetype: 'Reflect Wall', style: 'กำแพง',
    counters: ['ao-seara-tiana-liebli-bastet', 'ao-zaiross-tiana-galleon-lushen'],
    name: 'Irene Skogul Woosa Perna', nameTh: 'ไอรีน สโกกุล วูซ่า เพอร์น่า',
    slots: ['Irene', 'Skogul', 'Woosa', 'Perna'],
    winCondition: 'ลีด ACC 55% อารีน่า + Irene S2 สะท้อนดีบัฟ/ดึงความสนใจ, S3 ล้างบัฟ+ดูดเกจตัวอันตราย Skogul ยืน Woosa/Perna ลาก',
    runeBuilds: 'Irene Vio/Will HP% SPD ACC%, ที่เหลือ Vio/Will HP%',
    counterTips: 'บอมบ์คลีฟ หรือคลีฟที่ Tiana เร็วกว่า Irene',
    description: 'กำแพงที่ทีมบุกสาย CC จะโดนดีบัฟตัวเองสะท้อนกลับ',
    swaps: { Irene: ['Layla'] } },
  { id: 'ad-oliver-giana-nana-perna', tier: 'A', archetype: 'LD Speed Threat', style: 'ดักสปีด', ldNote: 'Giana มืด 5★',
    counters: ['ao-leo-galleon-lushen-lushen', 'ao-vanessa-tiana-galleon-zaiross'],
    name: 'Oliver Giana Nana Perna', nameTh: 'โอลิเวอร์ เกียน่า นาน่า เพอร์น่า',
    slots: ['Oliver', 'Giana', 'Nana', 'Perna'],
    winCondition: 'ลีด SPD 33% → Giana ล้างบัฟ+สตัน AoE → Oliver ดันคูลดาวน์+ดูดเกจ → Nana/Perna ชุบถ้าพลาด',
    runeBuilds: 'Giana Swift/Will ACC%, Oliver Swift/Will, Nana Vio/Will HP%, Perna Vio/Will',
    counterTips: 'Katarina ลีด RES + Will, หรือ Leo cleave',
    description: 'ดักสปีดสายมืดที่มีชุบสองชั้น กลับมาชนะได้แม้โดนคลีฟไม่จบ',
    swaps: { Giana: ['Clara'], Nana: ['Taranys', 'Woosa'] } },
  { id: 'ad-ganymede-skogul-woosa-perna', tier: 'A', archetype: 'ATB Control Wall', style: 'กำแพง',
    counters: ['ao-seara-tiana-liebli-bastet', 'ao-vanessa-tiana-galleon-zaiross'],
    name: 'Ganymede Skogul Woosa Perna', nameTh: 'แกนีมีด สโกกุล วูซ่า เพอร์น่า',
    slots: ['Ganymede', 'Skogul', 'Woosa', 'Perna'],
    winCondition: 'ลีด ACC 55% + Ganymede S3 ลดเกจ+ดันคูลดาวน์ AoE ไม่สน RES ทีมบุกใช้สกิล 3 ไม่ได้ → กำแพงลากจนชนะ',
    runeBuilds: 'Ganymede Vio/Will SPD HP% HP%, ที่เหลือ Vio/Will',
    counterTips: 'บอมบ์ที่วางได้ก่อน Ganymede ได้เทิร์น หรือคลีฟที่เร็วกว่า Ganymede (ลีด RES ไม่ช่วยกับ S3 Ganymede)',
    description: 'กำแพงที่ปิดสกิลสำคัญของทีมบุกด้วยการดันคูลดาวน์',
    swaps: { Ganymede: ['Psamathe', 'Daphnis'] } },
  { id: 'ad-laima-rakan-skogul-woosa', tier: 'A', archetype: 'LD Immunity Wall', style: 'กำแพง', ldNote: 'Laima แสง 5★',
    counters: ['ao-zaiross-tiana-galleon-lushen', 'ao-oberon-tiana-galleon-lushen'],
    name: 'Laima Rakan Skogul Woosa', nameTh: 'ไลม่า ราคาน สโกกุล วูซ่า (กำแพงแสง)',
    slots: ['Laima', 'Rakan', 'Skogul', 'Woosa'],
    winCondition: 'Laima S3 ล้างดีบัฟ+ภูมิคุ้มกัน+อมตะทีม (S2 ล้างบัฟ AoE) + Woosa ภูมิคุ้มกันซ้ำ ทีมบุกสาย CC/บอมบ์ไม่ติดเลย Rakan สวนกลับ',
    runeBuilds: 'Laima Vio/Will HP% SPD, Rakan Vio/Will, Skogul Vio/Will, Woosa Vio/Will',
    counterTips: 'Tiana ล้างอมตะ/ภูมิคุ้มกันแล้วคลีฟดาเมจล้วน (Lushen ×2)',
    description: 'กำแพงแสงที่บอมบ์และ CC ทำอะไรไม่ได้ ต้องคลีฟดาเมจดิบผ่าน Tiana เท่านั้น',
    swaps: { Laima: ['Woosa', 'Velajuel'], Rakan: ['Feng Yan'] } },
  { id: 'ad-daphnis-skogul-woosa-perna', tier: 'B', archetype: 'Strip Wall', style: 'กำแพง',
    counters: ['ao-seara-tiana-liebli-bastet', 'ao-vanessa-tiana-galleon-zaiross'],
    name: 'Daphnis Skogul Woosa Perna', nameTh: 'ดาฟนิส สโกกุล วูซ่า เพอร์น่า',
    slots: ['Daphnis', 'Skogul', 'Woosa', 'Perna'],
    winCondition: 'Daphnis S3 ล้างบัฟ+เจาะเกราะเดี่ยว (ยอมเสียเลือดแลกโล่) + S2 ดันคูลดาวน์ AoE/ห้ามฮีล ลีด CR 33% อารีน่าให้ Perna/ตัวตี',
    runeBuilds: 'Daphnis Vio/Will HP% CD%, ที่เหลือ Vio/Will',
    counterTips: 'บอมบ์คลีฟ หรือ Tiana cleave ที่เร็วกว่า',
    description: 'กำแพงที่มีตัวล้างบัฟ+ดันคูลดาวน์ในตัวเดียว',
    swaps: { Daphnis: ['Ganymede', 'Psamathe'] } },
  { id: 'ad-woosa-charlotte-skogul-perna', tier: 'B', archetype: 'ATB Control Wall', style: 'กำแพง',
    counters: ['ao-vanessa-tiana-galleon-zaiross', 'ao-zaiross-tiana-galleon-kaki'],
    name: 'Woosa Charlotte Skogul Perna', nameTh: 'วูซ่า ชาร์ล็อต สโกกุล เพอร์น่า',
    slots: ['Woosa', 'Charlotte', 'Skogul', 'Perna'],
    winCondition: 'ลีด ACC 41% ของ Woosa ช่วยให้ Charlotte S3 ลดเกจ AoE + Glancing + เพิ่มเกจทีม และ S2 สตัน AoE ติดง่าย ทีมบุกเสียจังหวะ → กำแพงลาก',
    runeBuilds: 'Charlotte Vio/Will SPD ACC%, ที่เหลือ Vio/Will HP%',
    counterTips: 'Katarina ลีด RES / Will ครบ หรือคลีฟที่เร็วกว่า Charlotte',
    description: 'กำแพงสายลดเกจ ทีมบุกที่ไม่ได้เทิร์นเลยคือทีมบุกที่แพ้',
    swaps: { Charlotte: ['Poseidon', 'Verad'] } },
];

// ---------------------------------------------------------------------------------------------
function build(side, list) {
  return list.map((t) => {
    if (!Array.isArray(t.slots) || t.slots.length !== 4) throw new Error(`${t.id}: needs 4 slots`);
    const members = t.slots.map((n) => {
      const m = byName.get(n.toLowerCase());
      if (!m) throw new Error(`${t.id}: unknown monster "${n}"`);
      return m;
    });
    for (const [slot, alts] of Object.entries(t.swaps || {})) {
      if (!byName.has(slot.toLowerCase())) throw new Error(`${t.id}: swap key "${slot}" unknown`);
      for (const a of alts) if (!byName.has(a.toLowerCase())) throw new Error(`${t.id}: swap "${a}" unknown`);
    }
    const ldMembers = members.filter((m) => m.element === 'light' || m.element === 'dark').map((m) => m.name);
    const leader = leaderOf(t.slots[0]);
    const traits = teamTraits(t.slots, traitsOf);
    return {
      id: t.id, side, tier: t.tier, archetype: t.archetype, name: t.name, nameTh: t.nameTh,
      ...(t.speed ? { speed: t.speed } : {}), ...(t.style ? { style: t.style } : {}),
      leader: leader.text, leaderArena: leader.arena,
      slots: t.slots,
      ld: ldMembers.length > 0, ldMembers, ldNote: t.ldNote || '',
      ...(t.turnOrder ? { turnOrder: t.turnOrder } : {}),
      ...(t.winCondition ? { winCondition: t.winCondition } : {}),
      ...(t.runeGuidance ? { runeGuidance: t.runeGuidance } : {}),
      ...(t.runeBuilds ? { runeBuilds: t.runeBuilds } : {}),
      ...(t.bestAgainst ? { bestAgainst: t.bestAgainst } : {}),
      ...(t.avoidAgainst ? { avoidAgainst: t.avoidAgainst } : {}),
      ...(t.counterTips ? { counterTips: t.counterTips } : {}),
      description: t.description,
      swaps: t.swaps || {},
      ...(side === 'ao' ? { caps: traits } : { traits, counters: t.counters || [] }),
      source: 'community',
    };
  });
}

/** name → arena traits for every catalogue monster with a skill record (drives the counter search). */
export function buildMonsterTraits() {
  const out = {};
  for (const rec of Object.values(skills)) {
    if (!rec?.name || !byName.has(rec.name.toLowerCase())) continue;
    const tr = monsterTraits(rec);
    out[rec.name] = tr;
  }
  return Object.fromEntries(Object.entries(out).sort(([a], [b]) => a.localeCompare(b)));
}

export function buildArenaTeams() {
  const offense = build('ao', AO);
  const defense = build('ad', AD);
  const ids = [...offense, ...defense].map((t) => t.id);
  if (new Set(ids).size !== ids.length) throw new Error('duplicate team id');
  const aoIds = new Set(offense.map((t) => t.id));
  for (const d of defense) for (const c of d.counters) if (!aoIds.has(c)) throw new Error(`${d.id}: counter "${c}" is not an AO id`);
  return {
    meta: {
      title: 'Summoners War Arena Meta Teams (AO & AD)',
      note: 'สูตรจากคอมมูนิตี้ที่ตรวจชื่อ/ลีดสกิล/สกิลกับฐานข้อมูล SWM แล้ว — อารีน่าปกติไม่มีสถิติสาธารณะ จึงไม่มี % อัตราชนะ',
      updatedAt: new Date().toISOString().slice(0, 10),
      counts: { offense: offense.length, defense: defense.length, ld: [...offense, ...defense].filter((t) => t.ld).length },
    },
    offense,
    defense,
  };
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const data = buildArenaTeams();
  fs.writeFileSync(path.join(root, 'src/data/arenaMetaTeams.json'), JSON.stringify(data, null, 2) + '\n');
  const traits = buildMonsterTraits();
  fs.writeFileSync(path.join(root, 'src/data/arenaMonsterTraits.json'), JSON.stringify(traits) + '\n');
  console.log(`monster traits: ${Object.keys(traits).length} monsters`);
  console.log(`arena teams: ${data.meta.counts.offense} AO + ${data.meta.counts.defense} AD (${data.meta.counts.ld} use light/dark)`);
  const noArenaLead = [...data.offense, ...data.defense].filter((t) => !t.leaderArena).map((t) => `${t.id} (${t.leader})`);
  if (noArenaLead.length) console.log('leaders without arena effect (shown with ⚠️):\n  ' + noArenaLead.join('\n  '));
}
